### ISSUE TITLE
JavaScript feedback

### ISSUE THREAD

**Issue by cydstumpel** [CelinexPutte/fix-the-flow-interactive-website#3]
Hey Celine, ziet er goed uit! Heb twee feedback puntjes:

Weet je het verschil tussen `let` en `const`? 
https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/#:~:text=const%20are%20necessary.-,Let,var%20that%20we%20just%20covered.%20Let%27s%20consider%20why%20this%20is%20so.,-let%20is%20block

`let` is voor variabelen die kunnen veranderen; voor een Boolean (`true` of `false` bijvoorbeeld is dat handig)
`const` is voor variabelen die niet aangepast hoeven te worden, zoals een querySelector in de meeste gevallen. Al jouw `let`'s kunnen dus `const`'s worden. :)

https://github.com/CelinexPutte/fix-the-flow-interactive-website/blob/db5fc64ae1953e5d1c4f942bf96717a4e265e846/scripts/main.js#L3
Kan je niet een class gebruiken? Is makkelijker toch?

https://github.com/CelinexPutte/fix-the-flow-interactive-website/blob/db5fc64ae1953e5d1c4f942bf96717a4e265e846/scripts/main.js#L1
Hey :)

**Comment by CelinexPutte** [comment]
Justus heeft woensdag gezegd dat we voor nu `let` moesten gebruiken ipv `const`, vandaar.

**Comment by cydstumpel** [comment]
HAAAAA ik ga hem eens even toespreken :)

**Comment by CelinexPutte** [comment]
Ik hou het voor nu even op `let`.

En na de 'discussie' over classes van maandag laat ik rij 3 in JS ook zo staan 😋
