### ISSUE TITLE
console.log in je code

### ISSUE THREAD

**Issue by ju5tu5** [CelinexPutte/fix-the-flow-interactive-website#4]
https://github.com/CelinexPutte/fix-the-flow-interactive-website/blob/db5fc64ae1953e5d1c4f942bf96717a4e265e846/scripts/main.js#L1

Hi! Ik zie nog een console.log() in je code staan. Na het testen is het netter om die weg te halen ;)

**Comment by CelinexPutte** [comment]
Done
